[package]
name = "PortfolioValentines"
version = "0.1.0"
description = "Description for package PortfolioValentines"

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = "PortfolioValentines"
source = "PortfolioValentines.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "PortfolioValentines"
module = "PortfolioValentines"
runner = "wasi"
